### ISSUE TITLE
Issue Failed to send request or retrieve response.

### ISSUE THREAD

**Issue by ludaka** [MoUnlocks/MoUnlocks-Bypass-SourceCode-PHP#1]
Hey i have this issue using ideviceactivation 
its showing Failed to send request or retrieve response.
Can you make some turorial ?

**Comment by MiUnlockCode** [comment]
First send raptor to phone then try again .

**Comment by DrJapan** [comment]
I noticed that other unlock methods have two files. I've seen a RaptorActivation.pem and a RaptorActivationCA.pem, do we need the RaptorActivationCA.pem for this to work?

**Comment by potatonc** [comment]
> I noticed that other unlock methods have two files. I've seen a RaptorActivation.pem and a RaptorActivationCA.pem, do we need the RaptorActivationCA.pem for this to work?

this tool it work?

**Comment by DrJapan** [comment]
Nope

**Comment by cpablast** [comment]
> Nope

The tool works, I have tested and verified it unlocks.

**Comment by DrJapan** [comment]
Which device/devices did you use it on? Did you have to make any modifications to the code? What about the RaptorCA.pem that's missing?

**Comment by cpablast** [comment]
> Which device/devices did you use it on? Did you have to make any modifications to the code? What about the RaptorCA.pem that's missing?

Iphone x global, iphone 7g gsm.. No modification and there is no RaptorCA.pem needed

**Comment by gsmnouri** [comment]
> > Which device/devices did you use it on? Did you have to make any modifications to the code? What about the RaptorCA.pem that's missing?
> 
> Iphone x global, iphone 7g gsm.. No modification and there is no RaptorCA.pem needed

how you send raptor to the iPhone ? command please

**Comment by cpablast** [comment]
> > > Which device/devices did you use it on? Did you have to make any modifications to the code? What about the RaptorCA.pem that's missing?
> > 
> > 
> > Iphone x global, iphone 7g gsm.. No modification and there is no RaptorCA.pem needed
> 
> how you send raptor to the iPhone ? command please

To send raptor to phone you need to ssh intp the phone after jailbreak then copy and replace the raptor.. I didn't use any commands just winscp for easy access... If you use it the phone will be tethered, so afterwards you will need to make it untethered and add some files to fix icloud login...   Note that this method has already been patched you need to edit the php inorder to be able to use it again..

**Comment by ludaka** [comment]
> > > > Which device/devices did you use it on? Did you have to make any modifications to the code? What about the RaptorCA.pem that's missing?
> > > 
> > > 
> > > Iphone x global, iphone 7g gsm.. No modification and there is no RaptorCA.pem needed
> > 
> > 
> > how you send raptor to the iPhone ? command please
> 
> To send raptor to phone you need to ssh intp the phone after jailbreak then copy and replace the raptor.. I didn't use any commands just winscp for easy access... If you use it the phone will be tethered, so afterwards you will need to make it untethered and add some files to fix icloud login... Note that this method has already been patched you need to edit the php inorder to be able to use it again..

(already been patched you need to edit the php inorder to be able to use it again..) - what do you mean it won't work anymore ? and what we need to edit exactly

**Comment by cpablast** [comment]
it won't work anymore
