### ISSUE TITLE
MEID

### ISSUE THREAD

**Issue by F1R3W4LL404** [MoUnlocks/MoUnlocks-Bypass-SourceCode-PHP#2]
I cannot activate MEID devices with this, any solution?

**Comment by DrJapan** [comment]
I can't get any devices to activate.

**Comment by cpablast** [comment]
> I cannot activate MEID devices with this, any solution?

It is for gsm devices, so meid might activate without signal

**Comment by DrJapan** [comment]
I'm trying to use it on an iPod Touch and and iPad Pro. No luck.

**Comment by 3xtc** [comment]
i can help if want :)

**Comment by DrJapan** [comment]
> i can help if want :)
> 
> 

I would love any help you could throw my way. :) Chat on Discord? Has anyone tried this on an iPod Touch or iPad?

**Comment by cpablast** [comment]
The only thing I did was create a cmd to execute activation on the device but this is just server side, there are more executions required to make it full.. If you use this direct it will unlock the device but it will be tethered

**Comment by DrJapan** [comment]
> The only thing I did was create a cmd to execute activation on the device but this is just server side, there are more executions required to make it full.. If you use this direct it will unlock the device but it will be tethered

Do you know the executions to make it untethered? What cmd did you use?

**Comment by 3xtc** [comment]
> The only thing I did was create a cmd to execute activation on the device but this is just server side, there are more executions required to make it full.. If you use this direct it will unlock the device but it will be tethered

I can help make untether what your discord

**Comment by cpablast** [comment]
> > The only thing I did was create a cmd to execute activation on the device but this is just server side, there are more executions required to make it full.. If you use this direct it will unlock the device but it will be tethered
> 
> Do you know the executions to make it untethered? What cmd did you use?

I am not on discord, I am not sure how to make untethered but currently working with a dev to make it work

**Comment by DrJapan** [comment]
> > The only thing I did was create a cmd to execute activation on the device but this is just server side, there are more executions required to make it full.. If you use this direct it will unlock the device but it will be tethered
> 
> 
> 
> I can help make untether what your discord

Hsah420 - 40- 7597 5340 5031#0151

Cheers!

**Comment by 3xtc** [comment]
any free open source icloud tools ? other than oc34n r2

**Comment by 3xtc** [comment]
> > > The only thing I did was create a cmd to execute activation on the device but this is just server side, there are more executions required to make it full.. If you use this direct it will unlock the device but it will be tethered
> > 
> > 
> > I can help make untether what your discord
> 
> Hsah420 - [40- 7597 5340](tel:40- 7597 5340) 5031#151
> 
> Cheers!

What’s your discord

**Comment by DrJapan** [comment]
Can't you see it? You replied to the comment that has my discord.

**Comment by 3xtc** [comment]
W3RDNA#4418

**Comment by hemantsharmahs** [comment]
ios which supports? is it support latest 14.8?
