### ISSUE TITLE
RaptorActivation.pem placement

### ISSUE THREAD

**Issue by erfto1** [MoUnlocks/MoUnlocks-Bypass-SourceCode-PHP#7]
Hello, when I run the server on localhost it starts and works fine however raptor is not found on it

I'm on macOS 11.7.6 and /System is not modifiable (SIP disabled) and I don't have MobileActivation.framework at /System/Libraries/PrivateFrameworks/ either. There is MobileActivationMacOS.framework instead.

If you could help me out on this or see if it is a bug I would be very grateful.

Thanks

**Comment by cpablast** [comment]
You need to copy the .pem located in the raptor folder and replace the one in the location below in your phoe

==== instructions ====

Raptor Path: 'System/Library/PrivateFrameworks/MobileActivation.framework/Support/Certificates/RaptorActivation.pem'

**Comment by CDSQ** [comment]
You don’t need to look at the things of liars. They first ask for payment on the grounds that the code will be leaked if they are given. After payment, they will not be used at all, and then they will sit on the ground and ask for money. Even if you pay more, there is nothing, especially Notice! And the code is copied everywhere!
