### ISSUE TITLE
ideviceactivation command

### ISSUE THREAD

**Issue by DevCode01** [MoUnlocks/MoUnlocks-Bypass-SourceCode-PHP#9]
Hi everyone !

I'm on Mac and I would like to run the command who starts with : ideviceactivation

I need to install this on my Mac but I've some troubles.
I found an old repository (13 years) and I've some errors during the installation. There is an other way to install this ?
Thanks :)

**Comment by cpablast** [comment]
@DevCode01 download libi then use the ideviceactivation in it to run the command
